#!/bin/bash

. ./utils.sh



##### ##### ##### ##### ##### ##### ##### ##### 
#setup traps to clean up temporary files
tempdir=$(mktemp -d)
function cleanup {
  rm -rf "$tempdir"
}
trap cleanup EXIT
trap cleanup SIGINT



##### ##### ##### ##### ##### ##### ##### ##### 
function build_vms_tfvars {
  local json_file_name=$1
  local out_file_name=$2

  cat /dev/null $out_file_name
  cat <<EOF > $out_file_name
  #############################################
  #This file was automatically generated by $0.  
  #All edits will be lost.
  #############################################
EOF
  # print the start of the definition
  printf "all_vms ={\n" >> $out_file_name

  declare -i nof_objs=`jq -r '.|length' $json_file_name`
  echo "val: $nof_objs"


  local -i n=0

  for ((n=0; n < nof_objs; ++n )); do 

    local ts=`jq -r --argjson n $n  '.[$n]|"\(.name) \(.enabled)"' $json_file_name `
    print_info "$n -->  $ts"

    set $ts
    local name=$1
    local enabled=$2

    print_info $name $enabled $precious
    if [ $enabled == "no" ]; then
      print_info "Skipping the VM named $name"
      continue
    fi

    printf "  %s = {\n" $name >> $out_file_name

    for nm in name enabled precious image network user_data; do
      print_info $nm
      ts=`jq -r --arg n $n  --arg nm "$nm" '.[$n|tonumber].[$nm]' $json_file_name `
      print_info $ts
      printf "    %-12s      : \"%s\"\n" $nm $ts >> $out_file_name
    done

    for nm in sof_mem sof_disk; do
      print_info $nm
      local -i tn=`jq -r --arg n $n  --arg nm "$nm" '.[$n|tonumber].[$nm]' $json_file_name `
      print_info $tn
      (( tn *= 1024*1024*1024 ))
      print_info $tn

      printf "    %-12s      : \"%s\"\n" $nm $tn >> $out_file_name
    done


    printf "  },\n"           >> $out_file_name

  done
  # print the end of the definition
  printf "}\n" >> $out_file_name

}

##### ##### ##### ##### ##### ##### ##### ##### 
function create_backup_pool {
  local pool_name=`yq '.backup_pool.name' deployment_cfg.yaml`
  local pool_path=`yq '.backup_pool.path' deployment_cfg.yaml`
  local pool_size=`yq '.backup_pool.size' deployment_cfg.yaml`

  print_info "pool info: $pool_name $pool_path $pool_size "
  if virsh pool-info $pool_name >/dev/null 2>&1; then
    print_info "The pool named $pool_name already exists."
    return 0
  fi

  # define and start the pool
  virsh pool-create-as \
                --name $pool_name\
                --type dir\
                --source-path $pool_path\
                --target $pool_path
                #--print-xml
  if [ $? -ne 0 ]; then
    print_error "Failed the pool-create-as call for $pool_name."
    return 1
  fi

  return 0
}



##### ##### ##### ##### ##### ##### ##### ##### 
# Function to inform of usage
function usage {
  cat <<EOF
  more info here
EOF
  print_info  usage: $0 '{mac|papa}'
}


##### ##### ##### ##### ##### ##### ##### ##### 
#Extract the options
while getopts "h" c
do
	case "$c"
	in
		h) usage; exit 0 ;;
		#h) inBaseName=$OPTARG ;;
		\?) echo $USAGE; exit 2;;
	esac
done
shift `expr $OPTIND - 1`

if [ $# -ne 1 ];then
  print_error "Insufficient number of arguments"
  usage;
  exit 1;
fi

print_info "Defining the deployment."
print_info "host: $1"

##### ##### ##### ##### ##### ##### ##### ##### 
# transfer variables from the YAML to the tfvars 
cat /dev/null > terraform.tfvars

printf "platform_dns_name = \"%s\"\n" `yq '.common.platform_dns_name' deployment_cfg.yaml` >> terraform.tfvars
printf "platform_ip       = \"%s\"\n" `yq '.common.platform_ip' deployment_cfg.yaml` >> terraform.tfvars
printf "pool_storage      = \"%s\"\n" `yq '.common.pool_storage' deployment_cfg.yaml` >> terraform.tfvars

##### ##### ##### ##### ##### ##### ##### ##### 
# Create vms.tfvars from the configuration YAML
yq -o=json '.all_vms' deployment_cfg.yaml > ${tempdir}/t.json
build_vms_tfvars ${tempdir}/t.json vms.tfvars


##### ##### ##### ##### ##### ##### ##### ##### 
# Create the backup pool
if !  create_backup_pool ; then
  print_error "Failed to create the backup pool.  Aborting!"
  exit 1
fi

##### ##### ##### ##### ##### ##### ##### ##### 
# Start
terraform plan -out t.plan -var-file=images.tfvars -var-file=vms.tfvars -var "dev_host=$1"
if [ $? -ne 0 ]; then
  print_error "Failed to create the plan"
  exit 1
fi
terraform apply t.plan


print_info "Successful run!"
exit 0
