#!/bin/bash

. ./utils.sh


function build_vms_tfvars {
  local json_file_name=$1
  local out_file_name=$2

  cat /dev/null $out_file_name
  cat <<EOF > $out_file_name
  #############################################
  #This file was automatically generated by $0.  
  #All edits will be lost.
  #############################################
EOF
  # print the start of the definition
  printf "all_vms ={\n" >> $out_file_name

  declare -i nof_objs=`jq -r '.|length' $json_file_name`
  echo "val: $nof_objs"


  local -i n=0

  for ((n=0; n < nof_objs; ++n )); do 

    local ts=`jq -r --argjson n $n  '.[$n]|"\(.name) \(.enabled)"' $json_file_name `
    print_info "$n -->  $ts"

    set $ts
    local name=$1
    local enabled=$2

    print_info $name $enabled $precious
    if [ $enabled == "no" ]; then
      print_info "Skipping the VM named $name"
      continue
    fi

    printf "  %s = {\n" $name >> $out_file_name

    for nm in name enbabled precious image network user_data; do
      print_info $nm
      ts=`jq -r --arg n $n  --arg nm "$nm" '.[$n|tonumber].[$nm]' $json_file_name `
      print_info $ts
      printf "    %-12s      : \"%s\"\n" $nm $ts >> $out_file_name
    done

    for nm in sof_mem sof_disk; do
      print_info $nm
      local -i tn=`jq -r --arg n $n  --arg nm "$nm" '.[$n|tonumber].[$nm]' $json_file_name `
      print_info $tn
      (( tn *= 1024*1024*1024 ))
      print_info $tn

      printf "    %-12s      : \"%s\"\n" $nm $tn >> $out_file_name
    done


    printf "  },\n"           >> $out_file_name

  done
  # print the end of the definition
  printf "}\n" >> $out_file_name

}

yq -o=json '.all_vms' deployment_cfg.yaml > t.json

build_vms_tfvars t.json t.tfvars




exit 0
